// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEHP7ks5T1PJxtRyBdjss4o9A8dw5bsLk',
    appId: '1:46377947585:web:a9f7b6d5da751c1789df40',
    messagingSenderId: '46377947585',
    projectId: 'cummins-82686',
    authDomain: 'cummins-82686.firebaseapp.com',
    storageBucket: 'cummins-82686.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABV9rMinP68uOFmEcL6CKRcOaOxQcm1rQ',
    appId: '1:46377947585:android:e99d4445f9f8644689df40',
    messagingSenderId: '46377947585',
    projectId: 'cummins-82686',
    storageBucket: 'cummins-82686.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgkcNqQBPZIfQQOu5asVJmSx6ysCya6nI',
    appId: '1:46377947585:ios:238993080b384f9889df40',
    messagingSenderId: '46377947585',
    projectId: 'cummins-82686',
    storageBucket: 'cummins-82686.appspot.com',
    iosClientId: '46377947585-6bu59se4hpiviq3a6ttqhomci79unlq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cummins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgkcNqQBPZIfQQOu5asVJmSx6ysCya6nI',
    appId: '1:46377947585:ios:238993080b384f9889df40',
    messagingSenderId: '46377947585',
    projectId: 'cummins-82686',
    storageBucket: 'cummins-82686.appspot.com',
    iosClientId: '46377947585-6bu59se4hpiviq3a6ttqhomci79unlq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cummins',
  );
}
